spring.application.name=wacdo

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

JWT_SECRET=${JWT_SECRET}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/
springdoc.swagger-ui.path=/